version: '3.8'
services:
  sierra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sierra
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - sierradb
    env_file:
      - .env

  sierradb:
    image: postgres:latest
    container_name: sierradb
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - sierradb:/var/lib/postgresql/data

volumes:
  sierradb:
    name: sierradb-vol
